// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdmfrldxcntneutmgcsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkbWZybGR4Y250bmV1dG1nY3NqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3OTU5MjIsImV4cCI6MjA3MjM3MTkyMn0.Q3w4WG5jNt79Y6oCRAer1QM7Oi4UO9siCp8lHQXA1eo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});